name: Preview Deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  deploy_preview:
    type: deploy
    params:
      prod: false

  comment:
    type: github-comment
    needs: [deploy_preview]
    params:
      message: |
        ## Preview Deployment

        | | |
        |---|---|
        | **URL** | ${{ needs.deploy_preview.outputs.deploy_url }} |
        | **Alias** | ${{ needs.deploy_preview.outputs.deploy_alias_url }} |
        | **Deployment** | ${{ needs.deploy_preview.outputs.deploy_dashboard_url }} |
